### ISSUE TITLE
What if you have a plugin dependency that isn't on packagist?

### ISSUE THREAD

**Issue by a-barbieri** [valu-digital/wp-testing-tools#7]
What if you have a plugin dependency that isn't on packagist?

In my case is [Relevanssi](https://www.relevanssi.com/)

**Comment by esamattis** [comment]
If you only need the free version you can get it from [wpackagist](https://wpackagist.org/). The composer package name is `wpackagist-plugin/relevanssi`. All wordpress.org plugins are available like that.

But if you need the Premium version you can use the `wp-install --post-install` hook to install it manually. You can use whatever code you need to fetch the code and activate it using the WP CLI (`wp plugin activate relevanssi`). This should work because the hook is executed right before database dump is made so it should appear as activated before each functional test.

https://github.com/valu-digital/wp-testing-tools/blob/9d2b0387f100849b3434da1a269b868527491a3d/tools/wp-install#L42-L46

In WPGraphQL Polylang I use it to add custom languages to the testing installation via WP CLI:

https://github.com/valu-digital/wp-graphql-polylang/blob/a3e6bcf360b194731a199af9090c1f4f573feda8/composer.json#L35
https://github.com/valu-digital/wp-graphql-polylang/blob/a3e6bcf360b194731a199af9090c1f4f573feda8/tools/post-install

**Comment by a-barbieri** [comment]
Amazing answer. Thanks for your quick reply.

I wasn't aware of these methods. 🙏
